### ISSUE TITLE
WaveMonitor can leak exceptions into Qt and crashes PothosFlow

### ISSUE THREAD

**Issue by ashley-b** [pothosware/PothosPlotters#18]
When plotting data with no data type convert throws in WaveMonitorDisplay::handleSamples().
Other blocks log this as a warning, I assume they do this conversion in there work() method.
```
#0  0x00007fff983afdd0 in Pothos::BufferChunk::convert(Pothos::DType const&, unsigned long) const@plt () at /usr/local/lib64/Pothos/modules0.6/plotters/libWaveMonitor.so
#1  0x00007fff983b813c in WaveMonitorDisplay::handleSamples(Pothos::Packet const&) (this=0x1417bb0, packet=...) at /home/ashley/OpenSource/sdr/pothos/plotters/WaveMonitor/WaveMonitorWork.cpp:54
#2  0x00007fff983c38f9 in WaveMonitorDisplay::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at /home/ashley/OpenSource/sdr/pothos/build/plotters/WaveMonitor/WaveMonitor_autogen/EWIEGA46WW/moc_WaveMonitorDisplay.cpp:107
#3  0x00007ffff4fb68da in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#4  0x00007ffff58200db in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#5  0x00007ffff57d95dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#6  0x00007ffff57e0c74 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#7  0x00007ffff4f8e627 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#8  0x00007ffff4f9085b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#9  0x00007ffff4fdcdd3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#10 0x00007ffff0d84247 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#11 0x00007ffff0d845e8 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#12 0x00007ffff0d8467c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#13 0x00007ffff4fdce4f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#14 0x00007ffff4f8d60a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#15 0x00007ffff4f9527c in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#16 0x0000000000436d14 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/ashley/OpenSource/sdr/pothos/flow/PothosFlow.cpp:84
```

**Comment by guruofquality** [comment]
Hopefully this will make a difference: https://github.com/pothosware/PothosComms/commit/fca46378681011e5138b4abf1de1b0649fccb304 Stops the block from ever passing unspecified buffer types into the widget

**Comment by ashley-b** [comment]
Sorry for the delay. Seams all good, error is logged now.
Thanks.
